// Main data array for students by country
export const data = [
  { country: "United States", students: 68 },
  { country: "France", students: 21 },
  { country: "United Kingdom", students: 21 },
  { country: "Germany", students: 20 },
  { country: "Switzerland", students: 13 },
  { country: "Spain", students: 10 },
  { country: "Netherlands", students: 9 },
  { country: "India", students: 9 },
  { country: "Singapore", students: 8 },
  { country: "Ireland", students: 8 },
  { country: "Sweden", students: 7 },
  { country: "Australia", students: 7 },
  { country: "Canada", students: 6 },
  { country: "Finland", students: 5 },
  { country: "Mexico", students: 4 },
  { country: "Brazil", students: 4 },
  { country: "Saudi Arabia", students: 3 },
  { country: "Romania", students: 3 },
  { country: "Philippines", students: 3 },
  { country: "New Zealand", students: 3 },
];
// Country to continent mapping for the provided data
export const countryContinent = {
  "United States": "Americas",
  France: "Europe",
  "United Kingdom": "Europe",
  Germany: "Europe",
  Switzerland: "Europe",
  Spain: "Europe",
  Netherlands: "Europe",
  India: "Asia",
  Singapore: "Asia",
  Ireland: "Europe",
  Sweden: "Europe",
  Australia: "Oceania",
  Canada: "Americas",
  Finland: "Europe",
  Mexico: "Americas",
  Brazil: "Americas",
  "Saudi Arabia": "Asia",
  Romania: "Europe",
  Philippines: "Asia",
  "New Zealand": "Oceania",
};

// Country to emoji flag mapping (using regional indicator symbols)
export const countryFlag = {
  "United States": "🇺🇸",
  France: "🇫🇷",
  "United Kingdom": "🇬🇧",
  Germany: "🇩🇪",
  Switzerland: "🇨🇭",
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  India: "🇮🇳",
  Singapore: "🇸🇬",
  Ireland: "🇮🇪",
  Sweden: "🇸🇪",
  Australia: "🇦🇺",
  Canada: "🇨🇦",
  Finland: "🇫🇮",
  Mexico: "🇲🇽",
  Brazil: "🇧🇷",
  "Saudi Arabia": "🇸🇦",
  Romania: "🇷🇴",
  Philippines: "🇵🇭",
  "New Zealand": "🇳🇿",
};
